jukebox2web/jukebox2web/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',
    (r'^', include('library_manager.urls')),
    (r'^', include('jukebox_manager.urls')),
    url(r'^', include('favicon.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

jukebox2web/library_manager/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.files import File
from tempfile import NamedTemporaryFile
import mutagenwrapper


class Artwork(models.Model):
    image = models.ImageField(upload_to="Artwork", null=True, blank=True)

    def url(self):
        return self.image.url

    @classmethod
    def create(cls, data, name):
        print "Creating new artwork for : " + name
        with NamedTemporaryFile(mode="w+b",) as f:
            f.write(data)
            f.flush()
            o = cls()
            o.image.save("%s.jpg" % name, File(f), save=True)
            return o


class AlbumArtwork(Artwork):
    album = models.ForeignKey('Album', null=True, blank=True, related_name='+')

    @classmethod
    def add(cls, data, album):
        o = cls.create(data, album.name)
        o.album = album
        o.save()
        return o


class ArtistArtwork(Artwork):
    artist = models.ForeignKey('Artist', null=True, blank=True, related_name='+')

    @classmethod
    def add_existing_artwork(cls, data, artist):
        print "Adding existing artwork to " + artist.name
        o = cls()
        o.image = data
        o.artist = artist
        o.save()
        return o

    @classmethod
    def add_new_artwork(cls, data, artist):
        print "Adding new artwork to " + artist.name
        o = cls.create(data, artist.name)
        o.artist = artist
        o.save()
        return o


class SlotArtwork(Artwork):
    pass


class Artist(models.Model):
    name = models.CharField(name='name', max_length='100', default='unknown')
    date_added = models.DateTimeField(auto_now=True, editable=False)
    artwork = models.ForeignKey('ArtistArtwork', null=True, blank=True, related_name='+')

    def get_artwork_dict(self):
        d = []
        artist_artwork_request = ArtistArtwork.objects.filter(artist=self)
        for artist_artwork in artist_artwork_request:
            selected = (artist_artwork == self.artwork)
            d.append({'pk': artist_artwork.pk, 'url': artist_artwork.url(), 'selected': selected})

        artist_albums = []
        artist_albums_request = Album.objects.filter(album_artist=self)
        for album in artist_albums_request:
            artist_albums.append(album.get_artwork_dict())

        return {'pk': self.pk, 'name': self.name, 'artworks': d, 'albums': artist_albums}


class Album(models.Model):
    name = models.CharField(name='name', max_length='100', default='unknown')
    year = models.CharField(name='year', max_length='100', null=True, blank=True)
    album_artist = models.ForeignKey('Artist', null=True, blank=True)
    date_added = models.DateTimeField(auto_now=True, editable=False)
    number_of_tracks = models.IntegerField(name='number_of_tracks', null=True, blank=True)
    number_of_discs = models.IntegerField(name='number_of_discs', null=True, blank=True)
    artwork = models.ForeignKey('AlbumArtwork', null=True, blank=True, related_name='+')

    def get_artwork_dict(self):
        album_artwork_request = AlbumArtwork.objects.filter(album=self)
        d = []
        for album_artwork in album_artwork_request:
            selected = (album_artwork == self.artwork)
            d.append({'pk': album_artwork.pk, 'url': album_artwork.url(), 'selected': selected})
        return {'pk': self.pk, 'title': self.name, 'album_artist': self.album_artist.pk, 'artworks': d}


class Music(models.Model):
    title = models.CharField('title', max_length=100)
    artist = models.ForeignKey('Artist', null=True, blank=True)
    album = models.ForeignKey('Album', null=True, blank=True)
    year = models.CharField(name='year', max_length='100', null=True, blank=True)
    file_field = models.FileField(upload_to="Library")
    date_added = models.DateTimeField(auto_now=True, editable=False)
    track_number = models.IntegerField(name='track_number', null=True, blank=True)
    disc_number = models.IntegerField(name='disc_number', null=True, blank=True)

    def clean(self):
        file_path = self.file_field.path
        tags = mutagenwrapper.read_tags(file_path)

        self.title = tags.find('title', 'unknown')

        artist_name = tags.find('artist', 'unknown')
        artist, artist_created = Artist.objects.get_or_create(name=artist_name)

        album_artist_name = tags.find('albumartist', artist_name)
        album_artist, album_artist_created = Artist.objects.get_or_create(name=album_artist_name)

        album, album_created = Album.objects.get_or_create(name=tags.find('album', 'unknown'),
                                                           album_artist=album_artist)

        artwork = tags.find('pictures')

        if album_created:
            album.number_of_tracks = tags.find('tracktotal')
            album.number_of_discs = tags.find('disctotal')
            if artwork:
                album.artwork = AlbumArtwork.add(artwork, album)
            album.save()

        if (not album.artwork) and artwork:
            album.artwork = AlbumArtwork.add(artwork, album)
            album.save()

        if not artist.artwork:
            if album.artwork:
                artist.artwork = ArtistArtwork.add_existing_artwork(album.artwork.image, artist)
            artist.save()

        if (album_artist.pk != artist.pk) and (not album_artist.artwork):
            if album.artwork:
                album_artist.artwork = ArtistArtwork.add_existing_artwork(album.artwork.image, artist)
            album_artist.save()

        self.artist = artist
        self.album = album
        self.year = tags.find('year', 'unknown')
        self.track_number = tags.find('tracknumber')
        self.disc_number = tags.find('discnumber')
        self.save()

    def dict(self):
        return {"pk": self.pk, "title": self.title, "artist": self.artist.name, "album": self.album.name,
                "album_artist": self.album.album_artist.name, "number": self.track_number, "disc_nb": self.disc_number,
                "artwork": (self.album.artwork.url() if self.album.artwork else 'static/default_artwork.png'),
                "artwork_pk": (self.album.artwork.pk if self.album.artwork else 0),
                "url": self.file_field.url}

jukebox2web/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>4 Col Portfolio - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href='{% static 'bootstrap/css/bootstrap.min.css' %}' rel="stylesheet">

    <!-- Custom CSS -->
    <link href='{% static "css/4-col-portfolio.css" %}' rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Start Bootstrap</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Page Content -->
<div class="container">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Page Heading
                <small>Secondary Text</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Projects Row -->
    <div class="row">
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
    </div>
    <!-- /.row -->

    <!-- Projects Row -->
    <div class="row">
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
    </div>
    <!-- /.row -->

    <!-- Projects Row -->
    <div class="row">
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            </a>
        </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Pagination -->
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">&laquo;</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">&raquo;</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>
{% block javascript %}
<script src='{% static "javascript/index.js" %}'></script>
<script src='{% static "javascript/jquery.js" %}'></script>
<script src='{% static "bootstrap/js/bootstrap.min.js" %}'></script>
{% endblock %}
</body>
</html>

jukebox2web/templates/playlist_manager.html
<!DOCTYPE html>
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/html">
<head>
    <title>Playlist Manager</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.contextMenu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/image-picker.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static "css/jukebox/playlist_manager.css" %}">

    <script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jquery-ui.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jlayout/jquery.sizes.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jlayout/jlayout.border.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jlayout/jlayout.grid.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jlayout/jlayout.flexgrid.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jlayout/jlayout.flow.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jlayout/jquery.jlayout.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jquery.ui.position.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jquery.contextMenu.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jquery.scrollTo.min.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jquery.iframe-transport.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jquery.fileupload.js" %}'></script>
    <script type="text/javascript" src='{% static "js/image-picker.js" %}'></script>

    <script type="text/javascript" src='{% static "js/jukebox/playlist_manager_widgets.js" %}'></script>
    <script type="text/javascript" src='{% static "js/jukebox/playlist_manager.js" %}'></script>

</head>
<body>

<div data-layout='{"type": "border", "hgap": 3, "vgap": 3}' class="page_layout">

    <div data-layout='{"type": "border", "hgap": 3, "vgap": 3}' class="library_layout center">

        <div class="navigation">
            <img src="{% static "jukebox.png" %}" height="70" width="70" style="opacity: 0.8">
            <div id="lib_nav_container">
                <a class="nav_link" href="#">Playlist Manager</a>
                <a class="nav_link" href="#">Upload Manager</a>
                <br>
                <div class="searchform">
                    <button class="icon-search"></button>
                    <label id="search_label">
                        <input id="search_input" type="text" name="s" value="" placeholder="Search" autocomplete="off">
                    </label>
                </div>
                <div id="search_string"> Search : <span></span></div>
            </div>
        </div>

        <div class="artists_col west"></div>

        <div class="center library_col"></div>

        <div id="edit_music_dialog" title="Edit Music"></div>

        <div id="play_music_dialog" title="Play Music">
            <audio id="player" controls>
                Votre navigateur ne supporte pas lélément <code>audio</code> element.
                <source src="">
            </audio>
        </div>

        <div id="artist_artwork_dialog" title="Edit Artist Artwork">
            <form action="" id="artist_artwork_uploader" enctype="multipart/form-data" style="visibility: hidden">
                {% csrf_token %}
                <input id="artist_artwork_file_field" name="artwork_file_field" type="file">
                <input type="submit" value="Upload">
            </form>
        </div>

        <div id="album_artwork_dialog" title="Edit Album Artwork">
            <form action="" id="album_artwork_uploader" enctype="multipart/form-data" style="visibility: hidden">
                {% csrf_token %}
                <input id="album_artwork_file_field" name="artwork_file_field" type="file">
                <input type="submit" value="Upload">
            </form>
        </div>


    </div>

    <div class="east music_set_col">

        <div class="navigation">
            <div id="slots_nav_container">
                <a class="nav_link">Playlist Manager</a>
                <div class="styled-select">
                    <select class="set_select" id="set_select">
                        <option>1</option>
                        <option selected="selected">2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option>10</option>
                    </select>
                </div>
                <a href="#" class="btn_input" id="btn_edit" title="Edit current Music Set">
                    <i class="fa fa-pencil-square-o"></i>
                </a>
                <a href="#" class="btn" id="btn_add" title="Add new Music Set">
                    <i class="fa fa-plus-square-o"></i>
                </a>
                <a href="#" class="btn" id="btn_save" title="Save edited Music Set">
                    <i class="fa fa-floppy-o"></i>
                </a>
                <a href="#" class="btn" id="btn_playlist_editor" title="Go to the Edit Playlist page">
                    <i class="fa fa-table"></i>
                </a>
            </div>
        </div>

        <div id="add_music_set_dialog" title="Add Music Set">
            <p>
                <label for="title">Title</label>
                <input type="text" name="Name" id="title" value=""
                       class="text ui-widget-content ui-corner-all">
            </p>
        </div>

        <div id="playlist_editor_dialog" title="Edit Playlist">
            <p>
                <label for="select_A">A</label>
                <select id="select_A">
                    <option selected="selected">A</option>
                    <option>B</option>
                    <option>C</option>
                    <option>D</option>
                </select>
                <label for="select_B">B</label>
                <select id="select_B">
                    <option>A</option>
                    <option selected="selected">B</option>
                    <option>C</option>
                    <option>D</option>
                </select>
                <label for="select_C">C</label>
                <select id="select_C">
                    <option>A</option>
                    <option>B</option>
                    <option selected="selected">C</option>
                    <option>D</option>
                </select>
                <label for="select_D">D</label>
                <select id="select_D">
                    <option>A</option>
                    <option>B</option>
                    <option>C</option>
                    <option selected="selected">D</option>
                </select>
            </p>
        </div>


        <div class="slots_list">

            <div id="selected_set"> Music Set Selected : <a>2</a></div>

        </div>

    </div>

</div>

<form action="" id="uploader" enctype="multipart/form-data" style="visibility: hidden">
    {% csrf_token %}
    <input id="id_file_field" name="file_field" type="file">
    <p><input type="submit" value="Upload" /></p>
</form>
</body>
</html>

jukebox2web/templates/upload.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Music Upload</title>
    </head>
    <body>
    <!-- List of uploaded documents -->
    {#  kxjcnglkfnvq #}
    {% if musics %}
        <ul>
        {% for music in musics %}
            <li><a href="{{ music.file_field.url }}">
                {% if music.artwork %}
                <img src="{{ music.artwork.url }}" width="50" height="50"/>
                {% endif %}
                {{ music.title }} - {{ music.artist.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No musics.</p>
    {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'Upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.file_field.label_tag }} {{ form.file_field.help_text }}</p>
            <p>{{ form.file_field.errors }}
                {{ form.file_field }}

            </p>
            <p><input type="submit" value="Upload" /></p>
        </form>
    </body>
</html> 